Set required cucumber version to 1.0.0
Remove lib/#{Cuke4Duke::JAR_NAME} from files.  If not then you get this error:

$ jruby -S rake install
rake aborted!
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["lib/cuke4duke-0.4.4.jar"] are not files

Tasks: TOP => install
(See full trace by running task with --trace)